spring:
  application:
    name: HotelService
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5433/microservices-app
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082


