spring:
  application:
    name: SERVICE-REGISTRY
  main:
    banner-mode: off

server:
  port: 8079

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false