spring:
  application:
    name: UserService
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3300/microservices-app
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081


